# Generated by Django 3.0.4 on 2020-03-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200329_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='description',
            new_name='content',
        ),
    ]
