# Generated by Django 3.0.4 on 2020-03-29 19:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_documents_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='abstract',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
