# Generated by Django 3.0.4 on 2020-03-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200329_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='files',
            new_name='additional_files',
        ),
    ]
