# Generated by Django 3.0.4 on 2020-03-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200329_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='additional_files',
            field=models.ManyToManyField(to='app.Files'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='images',
            field=models.ManyToManyField(to='app.Images'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='tags',
            field=models.ManyToManyField(to='app.Tags'),
        ),
    ]
