# Generated by Django 3.0.4 on 2020-03-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
