# Generated by Django 3.0.4 on 2020-04-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200411_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='documents',
            name='publish_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.PublicationType'),
            preserve_default=False,
        ),
    ]
