# Generated by Django 3.0.4 on 2020-03-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200329_0435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
